import type { Metadata } from "next";
import "../globals.css";

import Header from "@/components/genui/Header";
import Footer from "@/components/genui/Footer";

export const metadata: Metadata = {
  title: "Supafast AI",
  description: "Generated by a caffine fueled developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
