import type { Metadata } from "next";
import "../globals.css";

import Header from "@/components/genui/Header";
import Footer from "@/components/genui/Footer";
import BubbleBackground from "@/components/genui/BubbleBackground";

export const metadata: Metadata = {
  title: "Supafast AI",
  description: "Generated by a caffine fueled developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <BubbleBackground />
        <div className="relative z-10">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
